version: '3'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: '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'
      MODEL: 'gpt-3.5-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      SINGLE_CHAT_REPLY_SUFFIX: '"\n--------------------------------\n🍧回答仅供参考，勿闲聊。\n📄小助理使用参考👇\n https://www.promptgenius.site"'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_CHAT_REPLY_SUFFIX: '"\n--------------------------------\n🍧回答仅供参考，勿闲聊。\n📄小助理使用参考👇\n https://www.promptgenius.site"'
      GROUP_NAME_WHITE_LIST: '["123", "富贵人家", "虎队项目孵化", "喫冰｜集团董事会", "幸福大家庭"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言简洁的与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      TZ: Asia/Shanghai
      # NIGHT_START_TIME: 01:00
      # NIGHT_END_TIME: 06:00
  #  volumes:
  #    - ./app.py:/app/app.py
